### ISSUE TITLE
Doesn't generate blog routes in dist folder

### ISSUE THREAD

**Issue by sts-ryan-holton** [garethredfern/nuxt-basic-blog#1]
Excellent example, except, when running `npm run generate`, the individual blog folders aren't generated in full static mode, is there a way to achieve this?

**Comment by aaronguernsey** [comment]
Hey @sts-ryan-holton :wave:, I think I came across the same thing (at least I hope I'm interpreting what you've said correctly).

This StackOverflow pointed me in the right direction: https://stackoverflow.com/questions/56927438/nuxt-generate-throws-error-for-dynamic-page-nuxt-js

You may need to add the dynamic routes in the `nuxt.config` file under the `generate` options. Further information on the generate config can be found in [Nuxt's documentation](https://nuxtjs.org/docs/2.x/configuration-glossary/configuration-generate#routes).

```
# nuxt.config.js
generate: {
    routes() {
      // getRoutes is imported at the top of the nuxt.config file
      return getRoutes()
    }
 }
```

```
# generateRoutes.js

export default async () => {
    const { $content } = require('@nuxt/content')
    const posts = await $content('posts', { deep: true }).only(['path']).fetch()

    // Add blog pages routes
    const totalBlogPages = Math.ceil(posts.length / 5)
    const blogsPaginationRoutes = []
    for (let i = 1; i <= totalBlogPages; i++) {
        blogsPaginationRoutes.push(`/scripts/page/${i}`)
    }

    // Concat routes and pagination
    const routes = [...blogsPaginationRoutes, ...posts]

    return routes
}

```

Hope this helps!

**Comment by 0xgdr** [comment]
@sts-ryan-holton did what @aaronguernsey suggested fix your issue? I haven't run into this problem but all the content is served from a single content folder in the example.
