### ISSUE TITLE
2 problems in article "Adding Pagination to a Nuxt Blog"

### ISSUE THREAD

**Issue by c53hzn** [garethredfern/nuxt-basic-blog#2]
Hi garethredfern

I found your solution on pagination in nuxt content blog: [Adding Pagination to a Nuxt Blog](https://redfern.dev/articles/adding-pagination-nuxt-content-blog/), it really helps a lot!

However I encountered 2 problems.

One is that the "getContent" method might return invalid data.

```Javascript
// use the % (modulus) operator to get a whole remainder
const lastPageCount = totalArticles % perPage;
```

When `totalArticles % perPage == 0` , the `lastPageCount` is `0`, which is not right, I suggest you change it to the following code
```Javascript
// use the % (modulus) operator to get a whole remainder
const lastPageCount = totalArticles % perPage == 0? perPage: totalArticles % perPage;
```

Problem number two is the \<pagination/\> component, in your article, you used `Math.floor(this.total / this.perPage)` for `totalPages`, actually this should be `Math.ceil(this.total / this.perPage)`, and I saw that you have corrected this in the source code, but not in your article. 

I would really appreciate it if you could modify your article. And thanks again for writing this amazing solution!

**Comment by 0xgdr** [comment]
Hi @c53hzn thank you for your feedback. I have updated the incorrect Math.floor I must have missed that one, sorry.

Could you just explain "the "getContent" method might return invalid data." a bit further for me please? I just want to make sure I understand what you have seen before I update the code. Thank you.

**Comment by c53hzn** [comment]
Hi @garethredfern 

Thank you for your reply!
Let's say `totalArticles` is 15, and `perPage` is 5, then the first 2 pages are OK, but when you go to the 3 page, the `getContent` method returns invalid data.

The problem is this part
```JavaScript
// use the % (modulus) operator to get a whole remainder
const lastPageCount = totalArticles % perPage;

const skipNumber = () => {
  if (currentPage === 1) {
    return 0;
  }
  if (currentPage === lastPage) {
    return totalArticles - lastPageCount;
  }
  return (currentPage - 1) * perPage;
};
```

 `lastPageCount = totalArticles % perPage`, here `lastPageCount = 15 % 5 = 0`, then `skipNumber = 15 - 0 = 15`, which means on the last page, all 15 articles will be skipped, then there will be no articles to display.

**Comment by samgabrail** [comment]
I ran into the same issue, and @c53hzn solved it correctly. Thank you.

**Comment by 0xgdr** [comment]
Thank you both for your input, https://github.com/garethredfern/nuxt-basic-blog/pull/3 updates the code with @c53hzn fix.
